version: "3.9"

networks:
    proprli:
        name: proprli

services:
    app:
        container_name: proprli-app
        build:
            context: ./docker/8.3
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        environment:
            - APP_ENV=${APP_ENV}
            - DB_HOST=postgres
            - DB_PORT=${DB_PORT:-5432}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        depends_on:
            - postgres
        networks:
            - proprli

    postgres:
        container_name: proprli-db
        image: postgres:16
        restart: always
        volumes:
            - ./docker/postgres/data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        networks:
            - proprli

    web:
        container_name: proprli-web
        image: nginx:stable-alpine
        restart: always
        ports:
            - "85:80"
        volumes:
            - ./src:/var/www/html
            - ./docker/nginx/api.conf:/etc/nginx/conf.d/default.conf
        networks:
            - proprli

    adminer:
        container_name: proprli-adminer
        image: adminer
        restart: always
        ports:
            - "8080:8080"
        depends_on:
            - postgres
        networks:
            - proprli
